version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: transactai_postgres
    restart: always
    environment:
      POSTGRES_DB: transactai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: transactai-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transactai_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: transactai
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend/transaction_categorization
      dockerfile: Dockerfile
    container_name: transactai_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: transactai_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

  create_db:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transactai_create_db
    command: python /app/create_tables.py
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: transactai
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - ./create_tables.py:/app/create_tables.py:ro

volumes:
  postgres_data:
  pgadmin_data:
